export const meta = {
  name: 'wash-junction-fast',
  description: 'FAST build-only pass over a group of Wash Junction asset scripts (no renders, no review)',
  phases: [{ title: 'Build', detail: 'one builder agent per script: stats-only drafts, one final bake' }],
}

const ROOT = '/home/user/Book/cheese-team/wash-junction'

const BRIEF = `You are building game-ready 3D props for "Wash Junction", a CTF map for the Cheese Team game: a desert highway truck-stop / cheese depot. Style: modern industrial with a little Old West (rusted steel, sun-faded paint, weathered wood). Realistic PBR, worn and dirty, NOT cartoon, NOT clean.

SPEED IS THE PRIORITY. The user said: NO RENDERING, faster. Never pass --render, never run kit/inspect.py, never render anything. Aim to finish your job in about 15 minutes.

Working directory: ${ROOT}
1. Read kit/KIT.md and src/flag_cheese.py (finished example). Look up recipe params in kit/materials.py only if needed.
2. Write ONE build script src/<script>.py (if it already exists from an earlier interrupted run, read it and continue from it instead of starting over). Several K.Asset(...) blocks per script are fine; each K.Asset() resets the scene.
3. Check with a draft (takes seconds, stats only, no image): blender -b -P src/<script>.py -- --draft   then read export/<Name>/_draft.report.json (tris vs budget, dims_xyz vs target_xyz, uv_coverage). Fix Python errors, budget and size problems. Since there are no images, get the geometry right by careful reasoning: check every part's position/orientation arithmetic, that parts touch (nothing floating), that FRONT details are on the +X side.
4. Final bake (once): nohup blender -b -P src/<script>.py > /tmp/<script>.log 2>&1 &   then wait with a Bash until-loop on the final report, e.g. until [ export/<Name>/SM_<Name>.report.json -nt src/<script>.py ]; do sleep 10; done  (timeout 600000; repeat if it times out; CPUs are shared with other agents so it may take several minutes). Check the log tail for Python errors and that every asset printed "[kit] OK". If a single asset fails, fix and re-run just it with --only Name.

RULES
- Only create/modify src/<script>.py and files under export/<your asset folders>/. Do NOT edit kit/. Do NOT run git. Do NOT touch other scripts or folders.
- Hard limits: triangle budget per asset; size = W x H x D metres => bbox X = D, Y = W, Z = H, within about +/-5% per axis (explain deliberate deviations in notes); Z up; FRONT faces +X; pivot bottom centre unless stated; [TEAM] parts use the team recipe (K.TEAM / team_cloth) so they land in the TeamPaint slot; emissive parts use K.GLOW; no text/numbers anywhere; UCX collision for anything larger than a pickup, walkable surfaces as solid boxes.
- Quality: real construction (lips, flanges, bolts, hinges, seams, welds, dents, sag), right recipe per part (bolts steel, castings iron, tyres rubber, timber wood, glass glass...), sensible colours and weathering params, irregularity via K.deform. Drop hidden/ground-contact faces.
- Be honest in your report: list known issues.`

const JOBS = [
  { script: 'flag_pedestal', tier: 'P1', spec: `NOTE: src/flag_pedestal.py already exists from an interrupted run and its draft looked good -- finish it and run the final bake.\nSM_FlagPedestal -- flag stand. Size W x H x D = 2.9 x 0.95 x 2.9 (diameter 2.9, height 0.95). 4000 tris, tex 2048. Spec: "Hex steel plinth, diamond-plate top, bolted base, emissive ring channel (Glow slot). [TEAM] trim."
Guidance: a heavy hexagonal steel plinth (2.9 across corners; the across-flats axis will be ~2.51 -- inherent to a hexagon, note it). Bolted base flange (slightly larger hex plate with anchor bolts/nuts into the ground), welded side plates with corner seams, a diamond-plate top deck (diamond recipe: lay the plate flat in local XY), a recessed circular ring channel in the deck (~1.5-1.7 m diameter) holding a frosted emitter ring (K.GLOW), the flag cheese (a 1.2 m wheel) sits in the middle. [TEAM] trim: e.g. the top perimeter band / kick plates in K.TEAM. Worn diamond plate (polished tops), rust at the base, dust. UCX: hex hull.` },
  { script: 'vault_door', tier: 'P1', spec: `NOTE: SM_VaultDoor_Open is ALREADY FINISHED (export/VaultDoor_Open) -- do not rebuild it; only finish and final-bake SM_VaultDoorFrame (use --only VaultDoorFrame).\nTwo assets.
(1) SM_VaultDoor_Open -- round bank-vault door, shown open (it stands on its own next to the frame). Size W x H x D = 3.7 x 3.7 x 0.7 (diameter 3.7, 0.7 thick; door face looks toward +X). 8000 tris (=> LOD1 is automatic), tex 2048. Spec: "16 edge locking bolts, 3-spoke handwheel, hinge blocks." Guidance: thick steel disc with a stepped (multi-ring) sealing edge, 16 big round locking bolts protruding from the rim, a 3-spoke handwheel at the centre of the outer face (+X) on a hub, the inner face (-X) with the bolt-throw mechanism (linkage bars, cover plate, bolts), massive hinge blocks/arm on one side (-Y) that may extend past the disc (note it). Brushed/scuffed steel, grime in the steps, worn edges.
(2) SM_VaultDoorFrame -- size W x H x D = 4.7 x 4.7 x 0.5: ring 4.7 outer / 4.0 inner diameter, 0.5 deep. Budget 3000 tris, tex 2048. Stepped inner bore matching the door, 16 bolt receiver holes/sockets, hinge mount blocks matching the door, mounting flange with anchor bolts. Players walk through it: UCX as a ring of convex segments with flat walkable bottom pieces (no gaps).` },
  { script: 'health_packs', tier: 'P1', spec: `Three assets SM_HealthPack_S / _M / _L -- health pickups: metal first-aid tins. Widths (W, along Y) 0.30 / 0.45 / 0.60; choose believable H and D (e.g. S 0.30 x 0.16 x 0.20, M 0.45 x 0.22 x 0.28, L 0.60 x 0.30 x 0.36 W x H x D). 1000 tris EACH, tex 1024 each. Spec: "Metal first-aid tins with a moulded cheese-wedge emblem (no text)." Guidance: pressed-steel tin boxes with a hinged lid (piano hinge or two hinges at the back), rolled/beaded edges, a front latch (+X) and a carry handle; L bigger with two latches, corner protectors, stamped ribs. The emblem: a raised/moulded cheese wedge (triangular prism with a few hole dimples, red-painted on sun-faded off-white enamel, or white wedge on a red panel -- choose one scheme consistently; NOT team colours). Chipped enamel to steel, dents, dust. One simple UCX box each.` },
  { script: 'ammo_packs', tier: 'P1', spec: `Three assets SM_AmmoPack_S / _M / _L -- ammo pickups. Widths (W, along Y) 0.30 / 0.45 / 0.60. 1000 tris EACH, tex 1024 each. Spec: "Olive steel ammo cans; crate for L; brass casings visible in M and L." Guidance: S = closed .30-cal style olive drab steel ammo can (long axis along Y, ~0.30 x 0.19 x 0.10 W x H x D), with the lever latch, hinge, folding handle, rubber gasket lip. M = .50-cal can (~0.45 x 0.25 x 0.16) with the lid open/hinged back showing brass cartridges (brass recipe) inside. L = wooden ammo crate with steel/rope handles (~0.60 x 0.30 x 0.40), lid ajar or off, rows of brass casings visible. Olive drab paint (#4b5320-ish), chipped to steel, scuffs, dust. No text/stencils. One simple UCX each.` },
  { script: 'resupply_cabinet', tier: 'P1', spec: `SM_ResupplyCabinet -- spawn-room resupply locker. Size W x H x D = 1.7 x 2.3 x 0.6. 5000 tris, tex 2048. Spec: "Open front, 3 shelves, emissive frame strip (Glow). [TEAM] body." Guidance: heavy sheet-steel cabinet open toward +X (no doors), thick frame around the opening with an inset emitter strip (K.GLOW) running around it, 3 lipped steel shelves inside (wear on the lips), back panel with vent slots/perforations, plinth/kick plate, top hood, side handles, small conduit box with cable on one side, anchor bolts. Body panels K.TEAM (chipped), frame/kick raw steel. UCX: back + sides + top + shelves as boxes.` },
  { script: 'lockers', tier: 'P1', spec: `SM_Lockers_1 -- one steel locker module; plus variant SM_Lockers_1_Open (door swung open ~100 degrees) built with A.build(variants=...) sharing the texture set (door parts in group "door", K.rotate_group). Size W x H x D = 0.42 x 1.95 x 0.50. ONLY 600 tris for each (closed and open) -- the open one needs interior faces too, so plan the budget. tex 1024. Spec: "Louvred door, handle, blank number plate, tiles side by side. [TEAM]." Guidance: must tile side by side (sides flush, nothing sticking out past 0.42 in Y), door on the +X face with louvre vents (a few slanted slats or notched geometry), lift handle, blank number plate, hinges on one side, body or door in K.TEAM, base plinth, top. Open variant: visible interior (back wall, a shelf, hook). UCX: box (open variant: body + door hulls via the variant returning point lists).` },
  { script: 'spawn_door_frame', tier: 'P1', spec: `SM_SpawnDoorFrame -- spawn exit frame. Size W x H x D = 3.2 x 3.4 x 0.5. 1500 tris, tex 2048. Spec: "Heavy steel frame with an emitter strip down each side. [TEAM]." Guidance: a portal around a ~2.2 x 2.9 m opening: built-up box-section jambs and header with bolted flanges/stiffeners, emitter strips (K.GLOW) down each inner jamb in inset channels, K.TEAM face plates, raw steel elsewhere, bolted base plates, cable conduit feeding the emitters, hazard-worn edges. Opening must be clear. UCX: jambs + header boxes.` },
  { script: 'water_tower', tier: 'P2', spec: `SM_WaterTower_Wood -- wooden water tower on a roof. Size W x H x D = 6 x 13 x 6. 12000 tris (LOD1 automatic), tex 2048. Spec: "Stave tank 5.4 diameter x 4.2 with steel hoops, conical rusted tin roof, four I-beam legs 5.2 tall with bracing, ladder, railed walkway, blank flat area facing +X." Guidance: classic NYC/railroad tank: vertical wooden staves (individual staves or faceted with grooves), 6-8 round steel hoop rods with lugs/turnbuckles, conical roof of rusted corrugated tin with seams, a finial/vent and an access hatch; the tank sits on timber joists on steel beams; four I-beam legs 5.2 m with X-bracing (rods or angles) and horizontal struts, bolted base plates (pivot = bottom of legs, the roof it stands on is NOT part of the model); a vertical ladder from the base to the walkway and up the tank; a railed walkway (timber deck) around the tank base; inlet/outlet pipe down through the structure; a blank flat painted panel on the tank facing +X for a logo decal. UCX: legs, solid walkway/platform, tank cylinder hull, roof cone.` },
  { script: 'windmill', tier: 'P2', spec: `Three assets.
(1) SM_Windmill_Pump -- American farm pumping windmill (Aermotor style). Size W x H x D = 4 x 13 x 4 (overall height with the wheel fitted is about 13 m). Budget for this mesh: 7000 tris (the spec gives 10k for the windmill incl. wheel), tex 2048. Tapered 4-post galvanised angle-steel lattice tower (about 4 m base to 0.6 m top) with horizontal girts and diagonal rod bracing, ladder up one leg, small wooden platform near the top, gearbox/crank head on a turntable, tail vane (boom + sheet vane), pump rod down the tower centre to a pump head and pipe at the base, concrete footings. The wheel faces +X. Report the hub position (in final asset space) in notes.
(2) SM_Windmill_Wheel -- 18-blade wheel, 4.6 diameter, separate mesh with pivot at the HUB (use pivot="center" and make the hub the bbox centre, or pivot="none" with the hub at the origin). Budget 3000 tris, tex 2048. Curved galvanised sheet blades riveted to steel arms and two rings, hub casting.
(3) SM_StockTank -- round galvanised stock tank, 3.9 diameter x 0.76 tall. Budget 2000 tris, tex 2048. Corrugated galvanised wall, rolled top rim, riveted seams, drain plug, optional murky water surface inside below the rim. Collision: walls as convex segments + floor.` },
  { script: 'billboard', tier: 'P2', spec: `SM_Billboard_2Post -- roadside billboard. Size W x H x D = 13.5 x 12 x 1.6. 6000 tris (LOD1 automatic), tex 2048. Spec: "Two I-beam posts, wooden back framing, catwalk with railing, 5 lamp arms, blank 13 x 4.6 face, weathered and peeling." Guidance: blank face toward +X (13 x 4.6, top at ~12 m), face panels with seams, peeling paper/paint patches revealing older layers and wood (paint recipe with under="wood" and flake), timber back framing grid, two rusted I-beam posts with base plates down to the ground, a catwalk (planks or grating) with railing along the bottom of the face, 5 goose-neck lamp arms with lamp heads aimed at the face, a ladder up one post. UCX: posts, catwalk (solid), face box.` },
  { script: 'sign_gantry', tier: 'P2', spec: `Two assets.
(1) SM_SignGantry -- highway sign gantry. Size W x H x D = 2 x 7.8 x 17 => bbox X = 17 (span), Y = 2, Z = 7.8. Follow this box literally: the span runs along X, so sign brackets face -Y; note this in notes. 8000 tris (LOD1 automatic), tex 2048. Spec: "Galvanised box-truss posts and span truss with catwalk." Guidance: two 4-chord lattice end posts (tube chords + diagonal web) on concrete pedestals with anchor bolts, a 3D box truss spanning 17 m, a grated catwalk with handrail along the sign side, vertical sign-mount Z-bars, light conduit. Galvanised with zinc bloom and some rust. UCX: posts, truss box, catwalk.
(2) SM_HighwaySign -- blank green highway sign 6 x 2.4 (W x H), depth about 0.15 incl. stiffeners, face toward +X. Budget 800 tris, tex 2048. Extruded aluminium plank segments, a white border stripe (border only, no text), back Z-bar stiffeners and clamps, faded and dirty reflective green.` },
  { script: 'semi_trailer', tier: 'P2', spec: `SM_SemiTrailer_DryVan -- 48 ft box trailer. Size W x H x D = 2.6 x 4.1 x 14.6 (bbox X = 14.6 length, nose toward +X). 10000 tris (LOD1 automatic), tex 2048. Pivot under the king-pin: use pivot="none" and model with the king-pin at x=y=0 and the ground at z=0 (king-pin about 0.9 m behind the front wall). Spec: "Corrugated white panels, logistic posts, rear swing doors with lock rods, landing gear, tandem axles, mud flaps, underride guard." Guidance: sheet-and-post white van (sun-faded, road grime on the lower half, rust streaks from rivets), external posts, top/bottom rails, roof bows, slightly rounded nose with gladhands, upper coupler plate + king-pin, landing gear legs with crank and sand shoes, tandem axle slider at the rear with 8 dual tyres on steel rims, mud flaps, rear frame with two swing doors, 4 lock rods with cam keepers and handles, hinges, door seals, ICC underride guard, marker lights. UCX: box body + undercarriage hulls.` },
  { script: 'semi_cab', tier: 'P2', spec: `SM_SemiCab_American -- long-nose American conventional tractor (Peterbilt 379 / Kenworth W900 style). Size W x H x D = 2.6 x 4.2 x 6.6 (bbox X = 6.6, nose toward +X). 15000 tris (LOD1 automatic), tex 2048. Spec: "Chrome grille and stacks, sleeper, fuel tanks, dual rear axles, sun-faded red." Guidance: long hood with chrome vertical-bar grille and chrome bumper, round headlights in chrome buckets, front fenders, chrome air cleaners, two tall chrome exhaust stacks behind the cab, two-piece windshield, doors with handles, west-coast mirrors on arms, sleeper box with small windows, cylindrical fuel tanks with steps under the doors, tandem drive axles with 8 tyres + front steer axle with 2, mud flaps, frame rails, fifth-wheel plate. Paint: sun-faded chalky red (more faded on hood/roof), chrome with pitting/dust, glass (glass recipe), black rubber, grime. UCX: cab/hood/sleeper hulls + chassis.` },
  { script: 'roof_sign', tier: 'P2', spec: `SM_RoofSignFrame -- rooftop sign structure. Size W x H x D = 14.5 x 3.6 x 1.5. 3000 tris, tex 2048. Spec: "Truss holding a 14 x 2.2 sign box with bulb sockets, blank face. [TEAM] box." Guidance: angle-iron truss frame standing on roof sleepers/base plates with diagonal back braces, holding a 14 x 2.2 sheet-metal sign box (~0.35 deep) whose sides/face are K.TEAM, with a row of marquee bulb sockets around the border (some with bulbs -- bulb recipe -- some empty/broken), blank face toward +X, rusty raw steel truss, conduit. UCX: box + truss hulls.` },
  { script: 'garage_rollup', tier: 'P2', spec: `SM_GarageRollUp_Half -- roll-up dock door hardware (no wall). Size W x H x D = 8.6 x 4.7 x 0.7. 3000 tris, tex 2048. Spec: "Coil housing, guide channels, curtain lowered ~0.6 m from the top. [TEAM] curtain." Interpretation: the curtain hangs only ~0.6 m below the coil housing, leaving the opening mostly clear (note this). Guidance: coil housing (rolled hood) across the top, two vertical guide channels with wall-mounting angles and bolts, the corrugated slat curtain (K.TEAM) with a bottom bar + rubber seal and a pull handle, chain hoist with hand chain on one side, brackets. UCX: housing box, two channels, curtain box.` },
  { script: 'cheese_rack', tier: 'P3', spec: `SM_CheeseRack -- timber cheese-aging rack, plus variant SM_CheeseRack_Empty (A.build(variants={"CheeseRack_Empty": lambda A, ob: K.delete_group(ob, "wheels")}) -- shares the texture set). Size W x H x D = 2.6 x 2.9 x 0.85. 8000 tris (LOD1 automatic), tex 2048. Spec: "Timber, 5 slatted shelves, ~16 wheels with mixed rinds." Guidance: rough-sawn timber uprights and cross-bracing, 5 shelves of spaced slats (nails), ~16 cheese wheels of mixed sizes and rinds (wax, bleu_rind, natural_rind; group="wheels"), some stacked, one cut; dusty, mould stains on the boards. Open side toward +X. UCX: uprights/frame hull + shelf boxes.` },
  { script: 'cheese_wheels', tier: 'P3', spec: `Three assets with three rind skins each (use skins=): SM_CheeseWheel_S (diameter 0.30, about 0.12 tall, 300 tris), SM_CheeseWheel_M (diameter 0.55, about 0.20 tall, 500 tris), SM_CheeseWheel_Wedge (a wedge cut from an M-size wheel, showing paste with holes, about 300 tris). tex 1024. Spec: "Three rinds (red wax, blue mould, natural); the wedge has holes." Default skin = red wax + cheddar paste; skins={"BlueMould": {WAX.name: bleu_rind, PASTE.name: bleu_paste}, "Natural": {WAX.name: natural_rind, PASTE.name: cheddar with a pale gouda colour}} so textures become T_CheeseWheel_S_*, T_CheeseWheel_S_BlueMould_*, T_CheeseWheel_S_Natural_*. Look at src/flag_cheese.py for the wheel profile, drips and hole technique; keep the budget (fewer segments). Pivot bottom centre. One simple UCX each.` },
  { script: 'cheese_crate', tier: 'P3', spec: `SM_CheeseCrate -- wooden cheese crate. Size W x H x D = 0.8 x 0.5 x 0.6. 400 tris, tex 1024. Spec: "Stencilled cheese wedge, no text, stackable." Guidance: plank construction (boards with grooves/gaps suggested by geometry or by board seams), corner posts or battens, metal corner straps, rusty nails, flat top and bottom so crates stack; stencil from K.stencil_image("wedge", "wedge") on the front (+X) and sides via the wood recipe decal param (create the image after K.Asset()). One UCX box.` },
  { script: 'containers', tier: 'P3', spec: `Two assets: SM_Container_20ft (W x H x D = 2.44 x 2.59 x 6.06, 3000 tris) and SM_Container_40ft (2.44 x 2.59 x 12.19, 4000 tris), tex 2048. Spec: "Corner castings, corrugation, lock rods." Guidance: ISO dry containers: trapezoidal corrugated side walls (K.corrugated kind="trap"), corrugated front end wall, roof with shallow dents, 8 corner castings with oval apertures, top/bottom side rails, corner posts, forklift pockets on the 20ft, door end facing +X with two doors, 4 vertical lock rods with cam keepers, handles and hinges, door gaskets. Faded classic colours (e.g. 20ft faded blue, 40ft faded rust-red), heavy rust streaks/patches, dents. UCX: one box each (closed).` },
  { script: 'container_open', tier: 'P3', spec: `SM_Container_40ft_Open -- 40 ft container with the doors swung open and a walkable interior. Size W x H x D = 2.44 x 2.59 x 12.19 (opened doors extend the bbox in Y -- note it). 6000 tris (LOD1 automatic), tex 2048. Spec: "Doors swung out, a walkable wooden floor, a hollow interior with collision, and a TeamPaint-style tint slot." Guidance: same construction language as a real ISO container (corner castings, trapezoidal corrugation inside and out, lock rods, hinges), doors open ~250 degrees folded back along the sides or ~100 degrees, interior: plank floor (wood recipe, worn, stained), corrugated inner walls, ceiling, front end wall; exterior paint uses the team recipe (TeamPaint slot) so the engine tints it, rust in the steel parts. UCX: floor box (walkable), two wall boxes, roof box, end-wall box, door boxes.` },
  { script: 'sandbags', tier: 'P3', spec: `Two assets: SM_Sandbags_Straight (W x H x D = 1.8 x 0.75 x 0.6) and SM_Sandbags_Corner (an L-shaped 90-degree corner of the same wall height/thickness; choose a footprint such as 1.8 x 1.8 or 1.2 x 1.2 legs and explain), 2000 tris each, tex 1024 (or 2048 if you can justify). Spec: "5 rows, slumped burlap." Guidance: 5 staggered courses (running bond), each bag a lumpy low-poly pillow with folded/tied ends and a seam, sagging over the bags below (K.deform), slight random rotation; burlap recipe with dust and dirt; a torn bag spilling sand is a bonus. UCX: one or two boxes each.` },
  { script: 'dumpster', tier: 'P3', spec: `SM_Dumpster -- front-load commercial dumpster. Size W x H x D = 2 x 1.45 x 1.7 (bbox X = 1.7). 2000 tris, tex 2048. Spec: "Green, rusted, one lid open, wheels." Guidance: steel bin with a sloped front, top flange/rim, vertical reinforcing ribs, side fork sleeves/pockets, two plastic lids (one closed, one flipped open), 4 casters, drain plug; faded green paint, heavy rust, dents, grime. Front +X. UCX: bin box + open lid hull.` },
  { script: 'cable_reel', tier: 'P3', spec: `SM_CableReel -- wooden cable drum standing on its flanges. Diameter 1.8 x 0.9 wide => bbox X = 1.8, Y = 0.9 (drum axis along Y), Z = 1.8. 1000 tris, tex 1024. Spec: "Rubber cable wrap." Guidance: two plank/plywood flanges with through-bolts and a centre arbor hole, barrel wrapped with thick black rubber cable (ridged wraps visible, a loose end hanging off), weathered wood, dust. UCX: cylinder hull.` },
  { script: 'pump_industrial', tier: 'P3', spec: `Two assets.
(1) SM_Pump_Industrial -- horizontal centrifugal pump + electric motor on a concrete plinth. Size W x H x D = 3.2 x 2.3 x 1.8. 6000 tris (LOD1 automatic), tex 2048. Spec: "Pump and motor on a concrete plinth, [TEAM] casing." Guidance: concrete plinth (concrete recipe, oil stains), steel baseplate with anchor bolts, pump volute casing in K.TEAM, motor with cooling fins, fan cowl and terminal box, coupling guard, flanged suction and discharge pipes with gate valves (handwheels), pressure gauge (blank face), conduit. UCX: plinth box + machine hulls.
(2) SM_Valve_Wheel -- a separate cast-iron valve handwheel, diameter about 0.45, budget 300 tris, tex 1024, pivot at the hub (pivot="center"), with a rim, 4-5 spokes, hub. One small UCX.` },
  { script: 'stairs_catwalk', tier: 'P3', spec: `Two assets.
(1) SM_StairSteel_Run -- steel stair. Size W x H x D = 2.2 x 5 x 7 (bbox X = 7 run, Y = 2.2, Z = 5 rise). 4000 tris, tex 2048. Spec: "Diamond-plate treads, channel stringers, handrails both sides, [TEAM] nosing." Guidance: two C-channel stringers, ~25 diamond-plate treads with K.TEAM nosing strips on each tread edge, pipe handrails on both sides (posts, top rail, mid rail), base plates and top landing brackets. Choose a direction (e.g. bottom step at +X rising toward -X) and note it. UCX: a sloped ramp hull for walking + handrail boxes.
(2) SM_Catwalk_2m -- a 2 m grating catwalk module that tiles end to end, width about 1.1 m, railings both sides (posts, top rail, mid rail, toe boards), grating floor (geometry bars or a grating look) on edge channels. Budget 1500 tris, tex 2048. UCX: solid floor box + railing boxes. Note the tiling axis.` },
  { script: 'railings', tier: 'P3', spec: `Two assets: SM_Railing_2m (W x H x D = 2 x 1.07 x 0.1, 300 tris) -- posts, top rail, mid rail, toe board, base plates; galvanised or yellow safety paint; tiles end to end. And SM_Railing_2m_Panel -- the same railing with a K.TEAM corrugated sheet panel infill (TeamPaint), about 400 tris. tex 1024 each. UCX: one box each.` },
  { script: 'culvert', tier: 'P3', spec: `Two assets.
(1) SM_BoxCulvert_2m -- precast concrete box-culvert segment. Size W x H x D = 4.6 x 3.8 x 2.44 (bbox X = 2.44 along the flow). 500 tris, tex 2048. Spec: "Board-formed concrete, joint lip, silt stain." Hollow rectangular section with ~0.3 m walls and inside corner haunches, tongue lip on one end and groove on the other, silt stain line inside (concrete recipe silt_h) and efflorescence. Walkable interior: UCX floor, walls and roof as separate boxes.
(2) SM_CulvertHeadwall -- concrete headwall 16.8 wide x 5.6 tall (choose depth ~0.9, note it) with an 8 x 3.8 opening centred at the bottom, top coping, weep holes, rebar rust stains, water/silt marks. Budget 1500 tris, tex 2048. UCX: wall pieces around the opening.` },
  { script: 'filing_cabinet', tier: 'P3', spec: `SM_FilingCabinet -- 4-drawer steel vertical file cabinet. Size W x H x D = 0.5 x 1.32 x 0.6. 600 tris, tex 1024. Spec: "Dented, one drawer ajar." Guidance: drawer fronts toward +X with pulls, blank label holders, lock cylinder at top, one drawer pulled out ~15 cm (its sides and a few hanging files visible), kick base, dents (K.deform), faded grey/olive paint with chips and rust. UCX: body box.` },
  { script: 'bollard_grate', tier: 'P3', spec: `Two assets: SM_Bollard -- diameter 0.26 x 1.2 tall, 200 tris, tex 1024: concrete-filled steel pipe bollard with domed cap, yellow paint chipped and scuffed, rust at the base (optional reflective bands, no text). SM_DrainGrate -- W x H x D = 1 x 0.05 x 0.5, 200 tris, tex 1024: cast-iron drain/trench grate in its frame, slots/bars, rust and dirt in the slots. UCX: cylinder / thin box.` },
  { script: 'razor_wire', tier: 'P3', spec: `SM_RazorWire_3m -- concertina razor wire. Size W x H x D = 3 x 0.7 x 0.6 (coil axis along Y). 2000 tris, tex 1024, A = K.Asset(..., alpha=True). Spec: "Alpha-tested strip, not modelled barbs." Guidance: a set of alpha cards (e.g. several cards arranged around the coil axis, or crossed cards) textured with a numpy-drawn image of overlapping wire loops with razor barbs (K.image_from_array + K.mat("card", img=..., size=..., look="galv")); optional thin steel stakes holding it. Make sure the alpha reads clearly in the preview. UCX: one box.` },
  { script: 'team_banner', tier: 'P3', spec: `SM_TeamBanner -- hanging cloth banner. Size W x H = 3 x 1.6 (depth small). 300 tris, tex 1024. Spec: "Fringed bottom edge, folds, [TEAM] cloth, blank centre." Guidance: a top pole/rod or sleeve with end caps and two hanging ropes, cloth (team_cloth recipe -> TeamPaint) with gentle vertical folds (K.deform on a K.grid), a fringed/zig-zag bottom edge in geometry, sun fade and dirt; face toward +X; keep the centre blank. UCX: thin box.` },
  { script: 'western', tier: 'P3', spec: `Two assets: SM_HitchingPost (W x H x D = 3 x 1 x 0.3, 500 tris) -- two weathered timber posts and a rough rail, riveted iron straps/caps and tie rings, set into the ground. SM_WaterTrough (2.4 x 0.6 x 0.7, 500 tris) -- timber-plank trough bound with riveted iron bands (or an iron trough on timber legs), murky water surface below the rim. tex 1024 each. Spec: "Weathered timber and riveted iron." UCX: boxes.` },
  { script: 'gas_pump', tier: 'P3', spec: `SM_RetroGasPump -- 1950s gas pump (Wayne / Tokheim style). Size W x H x D = 0.7 x 2 x 0.5. 2000 tris, tex 2048. Spec: "1950s, faded paint, cracked glass globe." Guidance: rounded-corner body on a plinth, dial window on the +X face (glass, blank dials -- no numbers), chrome trim strips, nozzle holster with rubber hose and nozzle, cracked milk-glass globe on top (milkglass recipe with cracks), faded two-tone paint (e.g. faded red + cream) with chips and rust. UCX: body hull.` },
]

const BUILD_SCHEMA = {
  type: 'object',
  properties: {
    script: { type: 'string' },
    assets: { type: 'array', items: { type: 'object', properties: {
      name: { type: 'string' }, built: { type: 'boolean' }, tris: { type: 'number' }, budget: { type: 'number' },
      dims_xyz: { type: 'array', items: { type: 'number' } }, target_xyz: { type: 'array', items: { type: 'number' } },
      notes: { type: 'string' } }, required: ['name', 'built'] } },
    summary: { type: 'string' },
    kit_requests: { type: 'array', items: { type: 'string' } },
    known_issues: { type: 'array', items: { type: 'string' } },
  },
  required: ['script', 'assets', 'summary'],
}

const REVIEW_SCHEMA = {
  type: 'object',
  properties: {
    pass: { type: 'boolean' },
    score: { type: 'number', description: '0-10 realism/quality score' },
    issues: { type: 'array', items: { type: 'object', properties: {
      asset: { type: 'string' }, severity: { type: 'string', enum: ['blocker', 'major', 'minor'] },
      issue: { type: 'string' }, fix: { type: 'string' } }, required: ['asset', 'severity', 'issue'] } },
    summary: { type: 'string' },
  },
  required: ['pass', 'issues', 'summary'],
}

function buildPrompt(job) {
  return `${BRIEF}

YOUR JOB: script = src/${job.script}.py (priority ${job.tier}).
${job.spec}

Return the structured result: script path, each asset (name like SM_Name, built true/false, tris, budget, dims_xyz, target_xyz, notes incl. any deliberate deviations / pivot info), a short summary, kit_requests, known_issues.`
}

function reviewPrompt(job, built) {
  return `You are a demanding art director and technical artist reviewing game assets for "Wash Junction" (Cheese Team CTF map): desert highway truck-stop / cheese depot, modern industrial with a little Old West. Realistic PBR, worn and dirty, NOT cartoon, NOT clean; it must sit next to Poly Haven photoscans.
Working directory: ${ROOT}. Conventions: Z up, FRONT faces +X, size W x H x D => bbox X = D, Y = W, Z = H (+/-5%), pivot bottom centre unless stated, [TEAM] parts in the TeamPaint slot, emissive parts in the Glow slot, UCX collision for larger props, LOD1 (SM_<Name>_LOD1.fbx) for > 5000 tris, files per asset: SM_<Name>.fbx, SM_<Name>.glb, T_<Name>_BaseColor/_Normal/_ORM.png, SM_<Name>_preview.jpg, SM_<Name>.report.json (variants share the textures of their base asset and live in its folder).

ASSETS UNDER REVIEW (script src/${job.script}.py):
${job.spec}

Builder's report: ${JSON.stringify(built).slice(0, 4000)}

DO:
1. Read every SM_*.report.json in the asset folders under export/ (tris vs budget, dims vs target, slots, ucx, files).
2. Read each SM_*_preview.jpg. Run blender -b -P kit/inspect.py -- export/<Folder>/SM_<Name>.glb for each asset and Read the _inspect sheet (4 views). Optionally downscale and Read a BaseColor texture (python3 + PIL) to judge texture quality.
3. Skim the build script for anything that contradicts the spec.
Judge: every spec feature present and recognisable; real-world construction and proportions; realism of materials and wear (no recoloured-primitive look, no plastic-clean surfaces); technical problems (holes, floating/intersecting parts that look wrong, inverted or black faces, z-fighting, stretched/smeared textures, wrong orientation, wrong pivot, missing TeamPaint/Glow, missing UCX/LOD1/files, budget or size violations).
Severity: blocker = broken/missing deliverable or spec violation; major = clearly unrealistic or a missing listed feature; minor = polish. pass = true only if there are no blocker or major issues. Give concrete fixes (what part, what change). Do NOT modify any files.`
}

function fixPrompt(job, built, review) {
  return `${BRIEF}

YOUR JOB: improve the existing script src/${job.script}.py (already built once by another agent) so the assets pass review.
${job.spec}

Previous builder report: ${JSON.stringify(built).slice(0, 3000)}

REVIEW FINDINGS (fix every blocker and major; fix minors if cheap):
${JSON.stringify(review.issues, null, 1).slice(0, 6000)}
Reviewer summary: ${review.summary}

Read the current script and the current previews first, then fix with drafts and do a final rebuild of the affected assets (--only Name works for the final build too). Verify with the preview and kit/inspect.py. Return the structured result for the whole script.`
}

phase('Build')
const want = Array.isArray(args) ? args : []
const jobs = JOBS.filter((j) => want.includes(j.script))
log(`fast build: ${jobs.map((j) => j.script).join(', ')}`)
const results = await pipeline(jobs,
  (job) => agent(buildPrompt(job), { label: `build:${job.script}`, phase: 'Build', schema: BUILD_SCHEMA }))
return results.map((r, i) => r || { script: jobs[i].script, failed: true })
